#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Dec 30 11:19:37 2019

@author: alma
"""
#to illustrate that switching, counterintuitively, increases the odds of winning.
#contestant choices are automated to allow for a large number of test runs, but could be
#changed to get user input
import random

doors = ['A', 'B', 'C']
num_runs = 30
runs = 0
choices = ["stay", "switch"]

switchAndWin = 0 #times winning if you switch
stayAndWin = 0 #times winning if you stay

while runs <= num_runs:
    prize = random.choice(doors)
    picked_door = random.choice(doors)
    #Monty open a door that was neither chosen nor containing the prize
    for door in doors:
        if door != prize and door != picked_door:
            openedDoor = door
            break
        
    #the contestant can either stay with picked_door or switch to the other unopened one
    stayOrSwitch = random.choice(choices)
    if stayOrSwitch == "stay":
        final = picked_door
        if final == prize:
            stayAndWin += 1
    else: #switch
        for door in doors:
            if door != openedDoor and door != picked_door:
                final = door
                if final == prize:
                    switchAndWin += 1
                break
                
    runs += 1
    
percentSwitchWin = (switchAndWin/num_runs) * 100
percentStayWin = (stayAndWin/num_runs) * 100

print("Odds of winning if you stay: " + str(percentStayWin))
print("Odds of winning if you switch: " + str(percentSwitchWin))
